stack: devgeniem/client-asiakas
description: Asiakas
version: 0.0.10

variables:
  redis_password:
    type: string
    min_length: 40
    from:
      vault: ${STACK}-redis-password
      random_string: 40
    to:
      vault: ${STACK}-redis-password
  mysql_password:
    type: string
    min_length: 40
    from:
      vault: ${STACK}-mysql-password
      random_string: 40
    to:
      vault: ${STACK}-mysql-password
  nginx_port:
    type: integer
    from:
      random_number:
        min: 8100
        max: 8200
  auth_key:
    type: string
    from:
      vault: ${STACK}-wp-auth_key
      random_string: 30
    to:
      vault: ${STACK}-wp-auth_key
  secure_auth_key:
    type: string
    from:
      vault: ${STACK}-wp-secure_auth_key
      random_string: 30
    to:
      vault: ${STACK}-wp-secure_auth_key
  logged_in_key:
    type: string
    from:
      vault: ${STACK}-wp-logged_in_key
      random_string: 30
    to:
      vault: ${STACK}-wp-logged_in_key
  nonce_key:
    type: string
    from:
      vault: ${STACK}-wp-nonce_key
      random_string: 30
    to:
      vault: ${STACK}-wp-nonce_key
  auth_salt:
    type: string
    from:
      vault: ${STACK}-wp-auth_salt
      random_string: 30
    to:
      vault: ${STACK}-wp-auth_salt
  secure_auth_salt:
    type: string
    from:
      vault: ${STACK}-wp-secure_auth_salt
      random_string: 30
    to:
      vault: ${STACK}-wp-secure_auth_salt
  logged_in_salt:
    type: string
    from:
      vault: ${STACK}-wp-logged_in_salt
      random_string: 30
    to:
      vault: ${STACK}-wp-logged_in_salt
  nonce_salt:
    type: string
    from:
      vault: ${STACK}-wp-nonce_salt
      random_string: 30
    to:
      vault: ${STACK}-wp-nonce_salt
  smtp_password:
    type: string
    from:
      vault: ${STACK}-smtp_password
      random_string: 30
    to:
      vault: ${STACK}-smtp_password
  google_cloud_storage_access_key:
    type: string
    from:
      vault: ${STACK}-google-cloud-storage-access-key
      random_string: 30
    to:
      vault: ${STACK}-google-cloud-storage-access-key
services:
  redis:
    extends:
      file: vendor/devgeniem/kontena-cluster-configs/stage/wp-kontena.yml
      service: redis
  web:
    image: gcr.io/geniem-stage/client-asiakas:stage
    extends:
      file: vendor/devgeniem/kontena-cluster-configs/stage/wp-kontena.yml
      service: web
    environment:
      SMTP_TLS: "on"
      SMTP_AUTH: "on"
      SMTP_FROM: no-reply@asiakas.fi
      SMTP_HOST: smtp.mandrillapp.com
      SMTP_PASSWORD: ${smtp_password}
      SMTP_PORT: 587
      SMTP_USER: hannu.kumpula@geniem.com
      PHP_SESSION_REDIS_DB: 2
      NGINX_REDIS_CACHE_TTL_DEFAULT: 200 301 302 15m
      SERVER_NAME: asiakas.stage.geniem.io
      CRON_URL: https://asiakas.stage.geniem.io/run-cron
      WP_HOME: https://asiakas.stage.geniem.io
      WP_SITEURL: https://asiakas.stage.geniem.io
      KONTENA_LB_VIRTUAL_HOSTS: asiakas.stage.geniem.io,*.asiakas.stage.geniem.io
      GOOGLE_CLOUD_STORAGE_BUCKET_NAME: asiakas-stage
      NR_APP_NAME: Kontena - Stage - asiakas - WPMS
      GOOGLE_CLOUD_STORAGE_ACCESS_KEY: ${google_cloud_storage_access_key}
      WP_BLOG_PUBLIC: 0

